"""
Project AETHERIS - Local Inference Engine Port
Abstracts local quantized LLM reasoning behind a typed protocol.
"""
from typing import Protocol, runtime_checkable, Dict, Any, Optional
from pydantic import BaseModel, ConfigDict, Field


class InferenceGenerationRequest(BaseModel):
    model_config = ConfigDict(frozen=True)
    system_prompt: str = Field(..., description="System context role and formatting rules")
    user_prompt: str = Field(..., description="Target telemetry or analytical query")
    temperature: float = Field(default=0.1, ge=0.0, le=1.0)
    max_tokens: int = Field(default=512, ge=1, le=4096)


class InferenceGenerationResult(BaseModel):
    model_config = ConfigDict(frozen=True)
    content: str = Field(..., description="Raw output generated by the model")
    prompt_tokens: int = Field(default=0)
    completion_tokens: int = Field(default=0)
    finish_reason: str = Field(default="stop")


@runtime_checkable
class InferencePort(Protocol):
    """Protocol boundary isolating high-level reasoning from local GGUF runtimes."""

    def is_available(self) -> bool:
        ...

    def generate(self, request: InferenceGenerationRequest) -> InferenceGenerationResult:
        ...